# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 6) do

  create_table "authorities", :force => true do |t|
    t.column "number",     :integer,                  :null => false
    t.column "label",      :string,   :default => "", :null => false
    t.column "host",       :string,   :default => "", :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "authorities", ["label"], :name => "index_authorities_on_label"
  add_index "authorities", ["number"], :name => "index_authorities_on_number"

  create_table "contracts", :force => true do |t|
    t.column "statement",  :text,     :default => "", :null => false
    t.column "label",      :string,   :default => "", :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "contracts", ["label"], :name => "index_contracts_on_label"

  create_table "identifiers", :force => true do |t|
    t.column "ark",          :string,   :default => "", :null => false
    t.column "url",          :string,   :default => "", :null => false
    t.column "comment",      :text
    t.column "metadata",     :text
    t.column "authority_id", :integer,                  :null => false
    t.column "contract_id",  :integer
    t.column "user_id",      :integer,                  :null => false
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  add_index "identifiers", ["ark"], :name => "index_identifiers_on_ark"
  add_index "identifiers", ["url"], :name => "index_identifiers_on_url"

  create_table "users", :force => true do |t|
    t.column "name",       :string,   :default => "",    :null => false
    t.column "password",   :string,   :default => "",    :null => false
    t.column "email",      :string,   :default => "",    :null => false
    t.column "admin",      :boolean,  :default => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "users", ["name"], :name => "index_users_on_name"

end
