# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 7) do

  create_table "authorities", :force => true do |t|
    t.column "number", :integer
    t.column "label",  :string
  end

  add_index "authorities", ["number"], :name => "index_authorities_on_number"

  create_table "contracts", :force => true do |t|
    t.column "statement", :string
    t.column "label",     :string
  end

  add_index "contracts", ["statement"], :name => "index_contracts_on_statement"

  create_table "identifiers", :force => true do |t|
    t.column "ark",         :string
    t.column "url",         :string
    t.column "comment",     :string
    t.column "metadata",    :text
    t.column "minter_id",   :integer
    t.column "contract_id", :integer
    t.column "user_id",     :integer
    t.column "created_on",  :datetime
    t.column "updated_on",  :datetime
  end

  add_index "identifiers", ["ark"], :name => "index_identifiers_on_ark"
  add_index "identifiers", ["url"], :name => "index_identifiers_on_url"
  add_index "identifiers", ["comment"], :name => "index_identifiers_on_comment"

  create_table "minters", :force => true do |t|
    t.column "label",        :string
    t.column "random",       :boolean
    t.column "prefix",       :string
    t.column "authority_id", :integer
  end

  create_table "roles", :force => true do |t|
    t.column "name",         :string
    t.column "label",        :text
    t.column "authority_id", :integer
    t.column "minter_id",    :integer
  end

  add_index "roles", ["name"], :name => "index_roles_on_name"

  create_table "users", :force => true do |t|
    t.column "name",     :string
    t.column "password", :string
    t.column "email",    :string
  end

  add_index "users", ["name"], :name => "index_users_on_name"

end
