# NOTE: database is not actually used!  We're going "slim model" for now, but this will be rectified in a later version
development:
  adapter: mysql
  database: noidman_development
  username: root
  password:
  host: localhost

test:
  adapter: mysql
  database: noidman_test
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  database: noidman_production
  username: root
  password: 
  host: localhost
